Douzone2th/JavaAndAlgorithms

jaebin/com/src/weeks_1/Test2.java

feat : 테스트 입니다.
보조 설명이나 질문 등 여러가지를 적을 수 있습니다.

feat : 테스트 입니다.

---

heesoo/Factorial.java
heesoo/test.java

feat : 1/25, 백준 알고리즘 : [10872번 팩토리얼문제]

---

jaebin/com/src/weeks_1/Baekjoon_1769.java
jaebin/com/src/weeks_1/Baekjoon_1769_1.java

알고리즘 분류 : 재귀 함수, 재귀 호출
제한조건을 잘읽고 자료형의 범위에 대해서 생각해야 하는 문제 였습니다.

feat : 1/26, 백준 알고리즘 : [1769번 3의 배수]

---

hanyong/src/bj10872.java
hanyong/src/bj1769.java

feat : 1/26, 백준 알고리즘 : [1769번 3의 배수 문제]

feat : 1/26, 백준 알고리즘 : [1769번 3의 배수 문제]

---

jaebin/com/src/weeks_2/Programmers_42587.java

feat : 2/1, 프로그래머스 레벨2 : [프린터 문제]
큐의 특징과 큐의 인덱스를 파악하는 큐를 만들어서 풀었습니다.
다른 방식으로 풀 수 있지 않을까? 고민이 되는 문제입니다. -> 우선순위 큐 ?, 큐의 인덱스를 찾을 수 있는 메소드?

feat : 2/1, 프로그래머스 레벨2 : [프린터 문제]

---

yunseong/algorithm/src/stack_queue/ProLv2_StockPrice.java
yunseong/algorithm/src/stack_queue/ProLv2_Truck.java
yunseong/algorithm/src/stack_queue/ProLv2_Truck2.java

하나는 반복문 하나 사용 - 변수명이 복잡, 코드길이가 짧음
하나는 반복문 두개 사용 - 변수명이 간단함, 코드길이가 김

feat : 2/4, 프로그래머스 레벨2 [다리를 지나는트럭 문제] - 방법 2개로 작성

---

jaebin/com/src/weeks_2/Programmers_42583.java

feat : 2/4, 프로그래머스 레벨2 : [다리를 지나는 트럭 문제]
함정이 많은 문제,
1.무한루프를 빠져나가는 조건
2. 트럭들의 무게 합을 구할때 안에 for문 하나 더쓰면 시간초과
3. 1초 증가를 처음 시작할때 해줘야함. 아니라면 루프를 나오고 또 무언가를 더해줘야함.
4. ★★★1초(경과시간)에 bridge_length 만큼 움직인다는 부연설명이 없었음.

feat : 2/4, 프로그래머스 레벨2 : [다리를 지나는 트럭 문제]

---

jaebin/com/src/weeks_3/Baekjoon_11899.java
jaebin/com/src/weeks_3/Baekjoon_4949.java
jaebin/com/src/weeks_3/큐_스택(2).md

feat : 2/7, 백준 알고리즘 : [11899번 괄호 끼워넣기 문제]

feat : 2/7, 백준 알고리즘 : [11899번 괄호 끼워넣기 문제]

---

jaebin/com/src/weeks_3/Baekjoon_5397.java

feat : 2/10, 백준 알고리즘 : [5397번 키로거 문제]

feat : 2/10, 백준 알고리즘 : [5397번 키로거 문제]

---

jaebin/com/src/weeks_3/Baekjoon_14713.java

feat : 2/11, 백준 알고리즘 : [14713번 앵무새 문제]
앵무새를 하나의 큐라고 생각하고
여러 앵무새를 큐의 목록들이라고 생각하여 풀었습니다.

feat : 2/11, 백준 알고리즘 : [14713번 앵무새 문제]

---

jaebin/com/src/weeks_3/큐_스택(2).md
jaebin/com/src/weeks_4/Baekjoon_2751.java
jaebin/com/src/weeks_4/정렬.md

feat : 2/14, 백준 알고리즘 : [2751번 수 정렬하기 2 문제]

feat : 2/14, 백준 알고리즘 : [2751번 수 정렬하기 2 문제]

---

jaebin/src/weeks_4/Baekjoon_1755.java
jaebin/정재빈.md

feat : 2/17, 백준 알고리즘 : [1755번 숫자놀이 문제]

feat : 2/17, 백준 알고리즘 : [1755번 숫자놀이 문제]

---

jaebin/src/weeks_4/Baekjoon_2075.java
jaebin/src/weeks_4/Baekjoon_2075_2.java
jaebin/src/weeks_4/우선순위큐.md
jaebin/src/weeks_4/정렬.md

feat : 2/18, 백준 알고리즘 : [2075번 N번째 큰 수 문제]

feat : 2/18, 백준 알고리즘 : [2075번 N번째 큰 수 문제]

---

jaebin/src/weeks_5/Baekjoon_11651.java

feat : 2/21, 백준 알고리즘 : [11651번 좌표 정렬하기 2 문제]

feat : 2/21, 백준 알고리즘 : [11651번 좌표 정렬하기 2 문제]

---

jaebin/src/weeks_5/Baekjoon_14729.java
jaebin/src/weeks_5/Baekjoon_14729_2.java

feat : 2/22, 백준 알고리즘 : [14729번 칠무해 문제]

feat : 2/22, 백준 알고리즘 : [14729번 칠무해 문제]

---

class_diagram/class_diagram/.gitignore
class_diagram/class_diagram/build.gradle
class_diagram/class_diagram/gradle/wrapper/gradle-wrapper.properties
class_diagram/class_diagram/gradlew
class_diagram/class_diagram/gradlew.bat
class_diagram/class_diagram/settings.gradle
class_diagram/class_diagram/src/main/java/Test.java
jaebin/src/weeks_5/Baekjoon_7795.java

feat : 2/23, 백준 알고리즘 : [7795번 먹을 것인가 먹힐 것인가  문제]

feat : 2/23, 백준 알고리즘 : [7795번 먹을 것인가 먹힐 것인가  문제]

---

jaebin/src/weeks_5/Baekjoon_13164.java

feat : 2/24, 백준 알고리즘 : [13164번 행복유치원 문제]

feat : 2/24, 백준 알고리즘 : [13164번 행복유치원 문제]

---

jaebin/src/weeks_5/Baekjoon_18310.java

feat : 2/25, 백준 알고리즘 : [18310번 안테나 문제]

feat : 2/25, 백준 알고리즘 : [18310번 안테나 문제]

---

jaebin/src/weeks_6/Baekjoon_2309.java
jaebin/src/weeks_6/완전탐색.md

feat : 2/28, 백준 알고리즘 : [2309번 일곱 난쟁이 문제]

feat : 2/28, 백준 알고리즘 : [2309번 일곱 난쟁이 문제]

---

jaebin/src/weeks_6/Baekjoon_1120.java

feat : 3/2, 백준 알고리즘 : [1120번 문자열 문제]

feat : 3/2, 백준 알고리즘 : [1120번 문자열 문제]

---

jaebin/src/weeks_6/Baekjoon_1476.java

feat : 3/3, 백준 알고리즘 : [1476번 날짜계산 문제]

feat : 3/3, 백준 알고리즘 : [1476번 날짜계산 문제]

---

jaebin/src/weeks_7/Baekjoon_1182.java

feat : 3/8, 백준 알고리즘 : [1182번 부분수열의 합 문제]

feat : 3/8, 백준 알고리즘 : [1182번 부분수열의 합 문제]

---

jaebin/src/weeks_7/Baekjoon_2503.java

feat : 3/9, 백준 알고리즘 : [2503번 숫자야구 문제]

feat : 3/9, 백준 알고리즘 : [2503번 숫자야구 문제]

---

jaebin/src/weeks_8/Baekjoon_1620.java

feat : 3/16, 백준 알고리즘 : [1620번 나는야 포켓몬 마스터 이다솜 문제]

feat : 3/16, 백준 알고리즘 : [1620번 나는야 포켓몬 마스터 이다솜 문제]

---

woohyeoung/weeks_8/0316_baekjoon1620.java

feat: 3/16, 백준알고리즘 : [1620번 나는야포켓몬마스터이다솜]

feat: 3/16, 백준알고리즘 : [1620번 나는야포켓몬마스터이다솜]

---

jaebin/src/weeks_8/Baekjoon_13414.java
jaebin/src/weeks_8/Baekjoon_13414_2.java
jaebin/src/weeks_8/Baekjoon_13414_3.java
jaebin/정재빈.md

feat : 3/17, 백준 알고리즘 : [13414번 수강신청]

feat : 3/17, 백준 알고리즘 : [13414번 수강신청]

---

woohyeoung/weeks_8/0317_baekjoon13414.java

feat : 3/17, 백준알고리즘 : [13414번 수강신청]

feat : 3/17, 백준알고리즘 : [13414번 수강신청]

---

jaebin/src/weeks_8/Programmers_42577.java

feat : 3/18, 프로그래머스 레벨 2 : [전화번호 목록]

feat : 3/18, 프로그래머스 레벨 2 : [전화번호 목록]

---

jaebin/src/weeks_9/baekjoon_14244.java

feat:3/21, 백준 알고리즘 : 14244번 트리 만들기

feat:3/21, 백준 알고리즘 : 14244번 트리 만들기

---

jaebin/src/weeks_9/Baekjoon_14244.java
jaebin/src/weeks_9/Baekjoon_14425.java

feat : 3/22, 백준 알고리즘 : [14425번 문자열 집합]

feat : 3/22, 백준 알고리즘 : [14425번 문자열 집합]

---

jaebin/src/weeks_9/Baekjoon_14425.java
jaebin/src/weeks_9/Baekjoon_9372.java

feat : 3/23, 백준 알고리즘 : [9372번 상근이의 여행]

feat : 3/23, 백준 알고리즘 : [9372번 상근이의 여행]

---

jaebin/src/weeks_9/Baekjoon_11725.java

feat : 3/24, 백준 알고리즘 : [11725번 트리의 부모찾기]

feat : 3/24, 백준 알고리즘 : [11725번 트리의 부모찾기]

---

jaebin/src/weeks_9/Baekjoon_15900.java

feat : 3/2, 백준 알고리즘 : [15900번 나무탈출]

feat : 3/2, 백준 알고리즘 : [15900번 나무탈출]

---

jiho/algorithms/src/Baekjun/Baekjoon_1436.java
jiho/algorithms/src/Baekjun/Baekjoon_4796.java

feat : 3/23 백준 알고리즘 : [ 1463번 1로 만들기 ]

feat : 3/23 백준 알고리즘 : [ 1463번 1로 만들기 ]

---

yunseong/algorithm/greedy/Bj4796_Camping.java

feat : 3/28 백준 알고리즘 [4796번 캠핑문제]

---

jaebin/src/weeks_10/Baekjoon_15651.java

feat : 4/1, 백준 알고리즘 : [15651번 N과M(3)]

feat : 4/1, 백준 알고리즘 : [15651번 N과M(3)]

---

jaebin/src/weeks_11/Baekjoon_17478.java

feat : 4/4, 백준 알고리즘 : [17478번 재귀함수가 뭔가요?]

feat : 4/4, 백준 알고리즘 : [17478번 재귀함수가 뭔가요?]

---

jaebin/src/weeks_11/Baekjoon_18511.java

feat : 4/5, 백준 알고리즘 : [18511번 큰 수 구성하기]

feat : 4/5, 백준 알고리즘 : [18511번 큰 수 구성하기]

---

jaebin/src/weeks_10/트리(2).md
jaebin/src/weeks_11/Baekjoon_5568.java
jaebin/src/weeks_11/분할정복.md

feat : 4/7, 백준 알고리즘 : [5568번 카드 놓기]

feat : 4/7, 백준 알고리즘 : [5568번 카드 놓기]

---

jaebin/src/weeks_11/Baekjoon_11729.java
jaebin/src/weeks_11/Baekjoon_5568.java

feat : 4/8, 백준 알고리즘 : [11729번 하노이 탑 이동 순서]

feat : 4/8, 백준 알고리즘 : [11729번 하노이 탑 이동 순서]

---

jaebin/src/weeks_12/Baekjoon_11170.java
jaebin/src/weeks_12/Baekjoon_16505.java
jaebin/src/weeks_12/Programmers_42842.java

feat : 4/11, 백준 알고리즘 : [11170번 0의 개수]

feat : 4/11, 백준 알고리즘 : [11170번 0의 개수]

---

jaebin/src/weeks_12/Baekjoon_1065.java

feat : 4/13, 백준 알고리즘 : [1065번 한수]

feat : 4/13, 백준 알고리즘 : [1065번 한수]

---

jaebin/src/weeks_14/Baekjoon_1543.java

feat : 4/26, 백준 알고리즘 : [1543번 문서검색]

feat : 4/26, 백준 알고리즘 : [1543번 문서검색]

---

jaebin/src/weeks_14/Baekjoon_1094.java
jaebin/src/weeks_14/Baekjoon_11047.java
jaebin/src/weeks_14/Baekjoon_1543.java
jaebin/src/weeks_14/Baekjoon_2607.java

feat : 4/27, 백준 알고리즘 : [11047번 동전0]

feat : 4/27, 백준 알고리즘 : [11047번 동전0]
